/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LLMProvider = IDL.Variant({
  'Mistral' : IDL.Null,
  'Groq' : IDL.Null,
  'OpenAI' : IDL.Null,
  'Anthropic' : IDL.Null,
  'Gemini' : IDL.Null,
});
export const AgentId = IDL.Text;
export const Principal = IDL.Principal;
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AgentProfile = IDL.Record({
  'id' : AgentId,
  'bio' : IDL.Text,
  'personality' : IDL.Text,
  'owner' : Principal,
  'interests' : IDL.Vec(IDL.Text),
  'avatarSeed' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'llmProvider' : LLMProvider,
  'customPrompt' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
  'avatarPhoto' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'isVerified' : IDL.Bool,
  'verificationPhoto' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgent' : IDL.Func(
      [IDL.Text, IDL.Text, LLMProvider, IDL.Text],
      [AgentId],
      [],
    ),
  'getAgent' : IDL.Func([AgentId], [AgentProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAgents' : IDL.Func([], [IDL.Vec(AgentProfile)], ['query']),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadAgentAvatar' : IDL.Func([AgentId, ExternalBlob], [], []),
  'uploadAgentAvatarPhoto' : IDL.Func([AgentId, ExternalBlob], [], []),
  'verifyUser' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LLMProvider = IDL.Variant({
    'Mistral' : IDL.Null,
    'Groq' : IDL.Null,
    'OpenAI' : IDL.Null,
    'Anthropic' : IDL.Null,
    'Gemini' : IDL.Null,
  });
  const AgentId = IDL.Text;
  const Principal = IDL.Principal;
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AgentProfile = IDL.Record({
    'id' : AgentId,
    'bio' : IDL.Text,
    'personality' : IDL.Text,
    'owner' : Principal,
    'interests' : IDL.Vec(IDL.Text),
    'avatarSeed' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'llmProvider' : LLMProvider,
    'customPrompt' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
    'avatarPhoto' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'isVerified' : IDL.Bool,
    'verificationPhoto' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgent' : IDL.Func(
        [IDL.Text, IDL.Text, LLMProvider, IDL.Text],
        [AgentId],
        [],
      ),
    'getAgent' : IDL.Func([AgentId], [AgentProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAgents' : IDL.Func([], [IDL.Vec(AgentProfile)], ['query']),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadAgentAvatar' : IDL.Func([AgentId, ExternalBlob], [], []),
    'uploadAgentAvatarPhoto' : IDL.Func([AgentId, ExternalBlob], [], []),
    'verifyUser' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };