/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgentId = string;
export interface AgentProfile {
  'id' : AgentId,
  'bio' : string,
  'personality' : string,
  'owner' : Principal,
  'interests' : Array<string>,
  'avatarSeed' : string,
  'name' : string,
  'createdAt' : Time,
  'llmProvider' : LLMProvider,
  'customPrompt' : string,
  'avatar' : [] | [ExternalBlob],
  'avatarPhoto' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export type LLMProvider = { 'Mistral' : null } |
  { 'Groq' : null } |
  { 'OpenAI' : null } |
  { 'Anthropic' : null } |
  { 'Gemini' : null };
export type Principal = Principal;
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'isVerified' : boolean,
  'verificationPhoto' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgent' : ActorMethod<[string, string, LLMProvider, string], AgentId>,
  'getAgent' : ActorMethod<[AgentId], AgentProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAgents' : ActorMethod<[], Array<AgentProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadAgentAvatar' : ActorMethod<[AgentId, ExternalBlob], undefined>,
  'uploadAgentAvatarPhoto' : ActorMethod<[AgentId, ExternalBlob], undefined>,
  'verifyUser' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];